### PR TITLE
Fix 32-bit Windows build

### PR DESCRIPTION
**Pull request by RyanGlScott**
The foreign import of `ShellExecuteW` didn't use the proper calling conventions on 32-bit Windows. This commit adds a bit of CPP magic to fix that.

Addresses an AppVeyor CI issue in #12.

### CODE REVIEW

**Comment by yamadapc** [comment]
Awesome!

**Comment by yamadapc** [comment]
@rightfold Try merging this when you have a minute.

**Comment by yamadapc** [comment]
Could you publish it?

**Comment by mgsloan** [comment]
Re-pinging @rightfold about publishing to hackage (necessary to merge https://github.com/commercialhaskell/stack/pull/1548)

**Comment by rightfold** [comment]
Sorry, took me some time as I forgot my Hackage password and had problems with e-mail. The new version is on Hackage now.

**Comment by mgsloan** [comment]
Thanks!

**Pull request merged**
