### PR TITLE
Improve package README/.cabal and add travis

### PR DESCRIPTION
**Pull request by yamadapc**
Hey. I want to use this package to add a feature to the `stack` build
tool. However, we need it to be on Stackage and I'd like to have this
improvements.

Would you enable travis for the build? I can then help you add it to
stackage.

The relevant PR is https://github.com/commercialhaskell/stack/pull/1548.

### CODE REVIEW

**Comment by yamadapc** [comment]
Link for the build https://travis-ci.org/yamadapc/open-browser

**Comment by rightfold** [comment]
Looks good.

I've never used Stackage nor Travis before, though, so I'll take a look at it when I get home (in a few hours).

**Comment by rightfold** [comment]
Added Travis.

**Comment by yamadapc** [comment]
Awesomeness; to add it to stackage all you need to do is open a PR adding yourself to the [`build-contraints.yaml` file](https://github.com/fpco/stackage/blob/master/build-constraints.yaml). This was my recent edit for my own packages: https://github.com/fpco/stackage/pull/1060/files

:+1: thanks for replying so quickly

**Comment by rightfold** [comment]
https://github.com/fpco/stackage/pull/1065

**Pull request merged**
