### PR TITLE
Revert "Use native Windows API call"

### PR DESCRIPTION
**Pull request by yamadapc**
This reverts commit 0edbe982f9dc207afc5ad5a50f4e16c0a8dc47d7.

### CODE REVIEW

**Comment by rightfold** [comment]
Why?

**Comment by rightfold** [comment]
This code is subject to shell injection. Won't merge.

**Comment by yamadapc** [comment]
Sorry for the delay; it's how https://github.com/pwnall/node-open/blob/master/lib/open.js#L36-L44 does it. Ah... Okay. I've no idea how to test for windows, but the build is failing on Windows CI for stack because of the foreign import.

Sorry; I was going to comment but got caught up for a second.

https://ci.appveyor.com/project/snoyberg/stack/build/1.0.822

**Comment by yamadapc** [comment]
Okay. `node-open` does escaping. Do you want to do it?

**Comment by rightfold** [comment]
I don't know much about Windows, so maybe the author of the Windows commit (@RyanGlScott) knows more.

I'm always skeptical about such escaping mechanisms because they may be impacted by global state such as user-specific settings (especially locale and code page).

**Comment by RyanGlScott** [comment]
I'll be away from my computer for a bit, but I can take a look at this when I get back. The issue appears to be related to how the Win32 API handles ANSI vs. Unicode on 32-bit Windows (which is what `stack`'s AppVeyor tests are using). I don't think a fix would be too difficult.

In any case, the proposed change would definitely *not* be portable. It relies on `cygstart`, which is a Cygwin/MSYS-ism. Running a shell script is also a non-starter, since the native Windows command-line doesn't have an `sh` equivalent. Isn't Windows just great? :)

**Pull request closed without merging**
